ARG CLOUD_SDK_VERSION
FROM google/cloud-sdk:${CLOUD_SDK_VERSION}

RUN set -eu && \
    apt-get update; \
    apt-get install jq kubectl -y --no-install-recommends; \
    rm -rf /var/lib/apt/lists/*; \
    :
